# Generated by Django 5.0.1 on 2024-01-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=20)),
                ('creature_type', models.CharField(max_length=20)),
                ('alignment', models.CharField(max_length=20)),
                ('armor_class', models.IntegerField()),
                ('hit_points', models.CharField(max_length=50)),
                ('speed', models.CharField(max_length=50)),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('saving_throws', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('damage_resistances', models.TextField(blank=True)),
                ('damage_immunities', models.TextField(blank=True)),
                ('senses', models.TextField(blank=True)),
                ('languages', models.TextField(blank=True)),
                ('challenge_rating', models.CharField(max_length=20)),
                ('experience_points', models.IntegerField()),
                ('special_abilities', models.TextField(blank=True)),
                ('actions', models.TextField(blank=True)),
            ],
        ),
    ]
