# Generated by Django 5.0.1 on 2024-02-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0003_delete_post_monster_condition_immunities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='raw_stat_block',
            field=models.TextField(blank=True),
        ),
    ]
