# Generated by Django 5.0.1 on 2024-02-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0004_monster_raw_stat_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('hit_points', models.IntegerField(default=10)),
                ('armor_class', models.IntegerField(default=10)),
                ('speed', models.IntegerField(default=30)),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('constitution', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
                ('actions', models.TextField(blank=True)),
                ('bonus_actions', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell_name', models.CharField(max_length=100)),
                ('spell_type', models.CharField(choices=[('DD', 'Damage Dealing'), ('HL', 'Healing'), ('UT', 'Utility')], max_length=2)),
                ('class_requirement', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('effect', models.CharField(blank=True, max_length=100, null=True)),
                ('cast_at_higher_levels', models.BooleanField(default=False)),
            ],
        ),
    ]
