# Generated by Django 5.0.1 on 2024-02-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0005_playercharacter_spell'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='casting_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_classes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_components',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_damage_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_effect_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_scaling_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_target',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='spell_type',
            field=models.CharField(choices=[('DD', 'Damage Dealing'), ('HL', 'Healing'), ('UT', 'Utility'), ('OT', 'Other')], max_length=2),
        ),
    ]
