# Generated by Django 5.0.1 on 2024-02-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0006_spell_casting_time_spell_spell_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='alignment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='armor_class',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='charisma',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='condition_immunities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='constitution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='creature_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='damage_immunities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='damage_resistances',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='dexterity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='experience_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='hit_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='intelligence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='languages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='saving_throws',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='senses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='special_abilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='special_abilities_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='strength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='wisdom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
