# Generated by Django 5.0.1 on 2024-02-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0009_monster_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='input_method',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
    ]
